# version: '3.8'

# services:
#   kong:
#     image: kong:2.6
#     environment:
#       KONG_DATABASE: "off"
#       KONG_DECLARATIVE_CONFIG: "/usr/local/kong/declarative/kong.yml"
#       KONG_PROXY_ACCESS_LOG: "/dev/stdout"
#       KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
#       KONG_PROXY_ERROR_LOG: "/dev/stderr"
#       KONG_ADMIN_ERROR_LOG: "/dev/stderr"
#       KONG_ADMIN_LISTEN: "0.0.0.0:8001"
#     volumes:
#       - ./kong.yml:/usr/local/kong/declarative/kong.yml
#     ports:
#       - "8000:8000"
#       - "8001:8001"
#     depends_on:
#       - node-service

#   node-service:
#     build:
#       context: ./node-service
#       dockerfile: Dockerfile
#     ports:
#       - "3001:3001"
#   ui-service:
#     build:
#       context: ./ui-service
#       dockerfile: Dockerfile
#     ports:
#       - "3000:3000"
  

version: '3.8'

services:
  kong:
    image: kong:2.6
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: "/usr/local/kong/declarative/kong.yml"
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
    volumes:
      - ./kong.yml:/usr/local/kong/declarative/kong.yml
    ports:
      - "8000:8000"
      - "8001:8001"
    depends_on:
      - node-service
      - ui-service

  node-service:
    build:
      context: ./node-service
      dockerfile: Dockerfile
    volumes:
      - ./node-service:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3001:3001" 

  ui-service:
    build:
      context: ./ui-service
      dockerfile: Dockerfile
    volumes:
      - ./ui-service:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
